<!DOCTYPE HTML>
<html>
<head>
<title>手指操管理员界面</title>
<link href="/css/style.css" rel="stylesheet" type="text/css" media="all" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 

</head>
<body>
<!-- contact-form -->	
<div class="message warning">
<div class="inset">
	<div class="login-head">
		<h1>管理员登录</h1>	
	</div>
	
		<form action="/admin/loginprocess" method="post">
			<li>
				<input type="text"  name="adminname" />
			</li>
			<li>
				<input type="password" name="password" />
			</li>
			<?php echo $this->errno?>
				<input type="submit"  value="Sign in" />
				<h4><a href="#">Lost your Password ?</a></h4>			
		</form>
		</div>					
	</div>
</body>
</html>